// <auto-generated />
namespace PassionProject.TravelWorlds.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class placeprovince : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(placeprovince));
        
        string IMigrationMetadata.Id
        {
            get { return "202302091711157_place-province"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
